### ISSUE TITLE
✏️ [TASK]: Add Ansible molecule setup for all roles in the collection

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/ansible-collection-infra#13]
### Task Description

Currently, in CI we only run molecule on a few of the roles:

https://github.com/UCL-MIRSG/ansible-collection-infra/blob/f350806e1d2df6afb7e16a40818eb4f3dc92b01a/tests/molecule/resources/converge.yml#L7-L17

We should set add molecule configurations for the remaining roles. This will require:

- updating the role README to reflect it is now part of a Collection rather than a standalone Role (remove the Requirements, Dependencies, License, and Author Information sections as these are now all in the README for the Collection instead)

- add the role to `tests/molecule/resources/converge.yml` (adding a tag that can be used to selectively run the role)

- add any preparation steps needed to `tests/molecule/resources/prepare.yml`

- add any verify steps to `tests/molecule/resources/verify.yml`

- add a workflow to run `molecule converge` on the role whenever it changes (see [existing role workflows](https://github.com/UCL-MIRSG/ansible-collection-infra/tree/main/.github/workflows) for examples)

For examples, see these PRs that add a molecule setup:
- #10 
- #11

```[tasklist]
### Related Work Items
- [ ] https://github.com/UCL-MIRSG/ansible-collection-infra/issues/91
- [ ] https://github.com/UCL-MIRSG/ansible-collection-infra/issues/50
- [ ] https://github.com/UCL-MIRSG/ansible-collection-infra/issues/90
```
The roles related to monitoring might need a different molecule setup (with two servers rather than the current single-server setup)

**Comment by p-j-smith** [comment]
closing as complete
